### ISSUE TITLE
Check: AEW 60 vs AEW 83 in synthesis of OSM-S-59 vs OSM-S-60

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#244]
@alintheopen To check: in the collected approaches to amide OSM-S-59
http://malaria.ourexperiment.org/osm_procedures/7140/Preparation_of_OSMS59.html
there's a reductive alkylation
http://malaria.ourexperiment.org/tcmdc_ap/7519
But presumably this reaction was intended to make OSM-S-60? Was the outcome actually a sample of OSM-S-59, or is this experiment linked to the wrong master page?
Related: are AEW 60 and AEW 83 the same?

**Comment by mattodd** [comment]
Just re-awakening this remaining Series 1 paper. If this can be dealt with easily, great. If it's fiddly, and if there is no impact on the paper, we can just close. Either way let's get rid of it.

**Comment by alintheopen** [comment]
AEW 83 and AEW 60 are both indeed the same - apologies for changing code. Both reactions 'worked' by TLC/NMR but the product could not be isolated.

Also they correspond to OSM-S-60 not 59, so I have removed the erroneous link from the master page, updated both ELN and corrected titles so that OSM-S-60 is no longer referenced. Also added a new comment.

**Comment by sdebbert** [comment]
Here you go!
Stefan

--

Stefan Debbert

Associate Professor
Department of Chemistry
233 Science Hall

711 E. Boldt Way
Lawrence University
Appleton, WI 54911
office phone: (920) 832-6939

stefan.debbert@lawrence.edu
-----------------------------------------




________________________________________
