### ISSUE TITLE
Free Compound Screening for antimicrobial activity

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#286]
The Community for Open Antimicrobial Drug Discovery's goal is to screen compounds from academic research groups from anywhere in the world for free. If you have samples of compounds it might be worth submitting them to the assay?

http://www.cambridgemedchemconsulting.com/news/index_files/9f44ce6df8413578d946b3097c9f5165-186.html

**Comment by mattodd** [comment]
Yes indeed. I met Matthew Cooper the other day in Sydney to talk about this
very initiative. Before I encourage Uni colleagues to submit their
compounds I had to clarify the IP position of the University of Sydney,
which is now happening - i.e. I am hoping for a blanket agreement that then
allows faculty to submit compounds without signing fresh bilateral
agreements each time. However, OSM compounds could easily be submitted, it
seems to me. As I understand it the default position is that after 18
months the data goes into the public domain: from the FAQ: "*Eighteen
months after the completion of the screening or as otherwise agreed between
the participant and CO-ADD the participant agrees that the chemical
structures and screening data shall be published in an open access database
for use by the community (CO-ADD database or CO-ADD partner database such
as ChEMBL <https://www.ebi.ac.uk/chembl/>).*"

On 25 March 2015 at 19:09, Chris Swain <notifications@github.com> wrote:

>  The Community for Open Antimicrobial Drug Discovery's goal is to screen
> compounds from academic research groups from anywhere in the world for
> free. If you have samples of compounds it might be worth submitting them to
> the assay?
>
>
> http://www.cambridgemedchemconsulting.com/news/index_files/9f44ce6df8413578d946b3097c9f5165-186.html
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/286>.
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/chemistry/research/todd.html | W
http://opensourcemalaria.org/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by mattodd** [comment]
Waiting on advice from Sydney Uni IP, but closing this issue. I think Open Source Malaria and any other open projects should strongly support what CO-ADD is doing, ideally through molecule submission.
