### ISSUE TITLE
SGS Reports on OSM Work saved to Figshare.

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#307]
@ErinSheridan has set the SGS boys some homework! The students are writing up their work with OSM as a short report. Once complete the reports will be uploaded to Figshare so that the DOI may be referenced in future work.

**Comment by ErinSheridan** [comment]
I've set a slightly flexible due date of July 17th (flexible because some of the boys are also working on another project over the holidays).  But the reports should all be uploaded during the week 20-24th July.

**Comment by alintheopen** [comment]
Great stuff.

**Comment by ErinSheridan** [comment]
Good news!  The students' reports have been finalised and uploaded to figshare.

 They can be viewed here http://dx.doi.org/10.6084/m9.figshare.1513845

**Comment by mattodd** [comment]
These reports are really excellent, by the way. It's important we connect them to the main body of OSM work. I've added a link to the wiki on Series 4, and I've uploaded the combined reports to the OSM Shared Data ELN [here](http://malaria.ourexperiment.org/osdd_malaria_shared/13746/Reports_from_the_Sydney_Grammar_School_OSM_Project_in_2015.html) though making it clear that the citation should go to Figshare, since that provides a DOI. Closing this issue.
