### ISSUE TITLE
Engagement and Planning for SGS class of 2015/16

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#311]
By term four (October 2015), the OSM team need to provide a synthetic plan for next year's project. @ErinSheridan @TrentWallis @mattodd will work together on this.

**Comment by ErinSheridan** [comment]
We're back at school this week and the boys are looking forward to getting started.  Have you guys got any ideas for the next project?

**Comment by mattodd** [comment]
Great! @alintheopen and I will catch up on this ASAP. To my mind there are a couple of things. One is the displacement reactions that are currently being attempted by our excellent TSP students (you can see the kind of thing in the most recent entries in the [ELN](http://malaria.ourexperiment.org/triazolopyrazine_se)) and the other is the possibility of taking the triazolopyrazine core (no pendant groups) and exploring what happens to it as you react it with something like bromine, in the way that [Tianyi had started](http://malaria.ourexperiment.org/the_osm_blog/8478/Summary_of_my_exchange_in_Mats_group.html). When exactly is Day 1 in the lab?

**Comment by ErinSheridan** [comment]
We can start in the lab as early as this Friday, but I still have another practice session that I'd like to do with the students this week.  No matter which direction we go in, it looks like we'll have to put in a chemical order so that might slow us up. That said, the boys are getting close to their exams so the week of 9th Nov might be the best time to make a good start.

Both of those projects look good, although we couldn't do any of the Suzuki couplings as we don't have a schlenk line, the other reactions all look doable.

**Comment by alintheopen** [comment]
One suggestion would be for the students to synthesise Daraprim (pyrimethamine) and some new analogues. This molecule has received a lot of press recently owing to the price hiking over in the USA. Turing pharmaceuticals wanted to raise the price from $13.50 to $750 per dose. Public and media outcry has led the company to reconsider the pricing options but a synthesis in the open would be great to see. Daraprim was originally synthesised as an antimalarial (by Nobel prize winner Gertrude Elion) and is now used in combination with a sulfonamide for the treatment of toxoplasmosis.

The students could synthesise pyrimethamine using the route highlighted below (nabbed from Wikipedia https://en.wikipedia.org/wiki/Pyrimethamine) but with supporting evidence found in the literature. Stronger bases are typically used for step one, and some routes use diazo compounds for step 2, but I think this method looks quite robust and uses reagents that are accessible and could be handled by the students under your supervision of course. We could potentially test all compounds against malaria (after designing some novel analogs), TB and also against toxoplasma gondii if we can set up a collaboration.
What do you think?
![daraprim](https://cloud.githubusercontent.com/assets/2626599/10362219/fe571114-6df8-11e5-9bab-0a1dd6d8d610.png)

**Comment by mattodd** [comment]
Fascinating idea. What do you think @ErinSheridan ? Chemistry doable? Might your students be interested in exploring how easy/difficult it is to make this important, topical compound?

**Comment by MedChemProf** [comment]
Excuse me for the question, but I thought the Daraprim and analog synthesis proposal was an excellent and very interesting idea. I was also intrigued because of the timeliness and I think I could get some of the Pharm.D. students to want to do some chemistry. What sort of timelines are you anticipating for the synthetic work to be completed within? Thank you.

**Comment by drc007** [comment]
An excellent idea. If you want you could also ask a few questions that could be explored,  is the first intermediate all in the keto tautomer? How would you determine the stereochemistry of the tetra-substituted double bond in the second intermediate?

**Comment by TrentWallis** [comment]
That looks like a great proposal to me!

**Comment by alintheopen** [comment]
Thanks for the nice ideas @drc007 - one thing I'm keen to push more this time is community engagement with the students and it would be good to have some mentors (such as your self or @MedChemProf) from a medchem background.

@MedChemProf it would be awesome if your students could be involved too. I might even involve a Sydney Uni contingent and we could all work on the project together - all we need is defined targets/goals for each group and then the more the merrier. I'll wait to hear more from @TrentWallis and @ErinSheridan and then I'll write up a more detailed proposal - but obviously feel very welcome to put any ideas down here. Exciting times! Cheers, Alice

**Comment by ErinSheridan** [comment]
This looks great!  It looks like they would be able to do the chemistry, and I love that it's been in the news recently.  And lots of scope for interesting chemistry.

**Comment by mattodd** [comment]
OK, let's do it! Super exciting. I guess you'd need to buy in the chemicals
Erin? Shall we start a new lab notebook ("Daraprim Synthesis") so that any
students can contribute? We could set up a forum for discussion or just use
the Open Source Malaria G+ page, as people wish. I agree 100% that the wise
oversight of current/former pharma people would be valuable.

On 9 October 2015 at 14:30, ErinSheridan <notifications@github.com> wrote:

> This looks great! It looks like they would be able to do the chemistry,
> and I love that it's been in the news recently. And lots of scope for
> interesting chemistry.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/311#issuecomment-146746377>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by alintheopen** [comment]
Sounds good. I can set up a new LabNotebook and I will also organise the files through an open LabArchives account so that @MedChemProf can clone the course for his students, although of course they can use labtrove too...everyone is welcome.

**Comment by MedChemProf** [comment]
@alintheopen - I am just thinking out loud at the moment after taking a quick read through some of the historical SAR of the 5-phenylpyrimidine-2,4-diamine core in regards to antimalarial activity. One thing that I did notice is that while there are a number of analogs at the 6-position of the 5-phenylpyrimidine-2,4-diamine core, there are very few analogs that have a 6-methylamino substituted group (example NC1=NC(CNCCCOC)=C(C2=CC=C(Cl)C=C2)C(N)=N1 ). I gravitated toward analogs of this nature largely because my students could easily run a series of reductive aminations on the carboxaldehyde precursor ( O=CC1=C(C2=CC=C(Cl)C=C2)C(N)=NC(N)=N1 ). I also did a quick series of dockings of some simple analogs using the 1-Click Docking tool at mCule.com against several DHFR isoforms and they seem palatable (at least they can be accommodated and also pick up some additional hydrogen bonds to the backbone of the proteins.) I am still trying to weigh the best synthetic pathway to the carboxaldehyde that would be amendable for my laboratory. Again, this is just a few of my thoughts that I thought I would put forward. Any discussion on more promising areas to work very welcomed.

**Comment by alintheopen** [comment]
Will mull this over, thanks Chase. For those who want to think about the reaction, here it is:
![daraprim chase](https://cloud.githubusercontent.com/assets/2626599/10469808/11f37f46-7254-11e5-845b-198cffa7616d.png)

**Comment by mattodd** [comment]
So @ErinSheridan - think you'll run with this? Ought we to source the compounds you guys would need? If you're going for it we can start a new ELN for the project, and see if we can secure a chemistry mentor, perhaps?

**Comment by ErinSheridan** [comment]
I think this is perfect, I'm looking at what chemicals we'll need now.  A mentor would be fantastic!

**Comment by MedChemProf** [comment]
It looks like @O_S_M already retweeted the notice, but I would be interested in working on a proposal to https://www.openscienceprize.org/ if someone is interested. Looks like one of the main requirements is to have at least 1 U.S. based collaborator and 1 based in another country. Please let me know if interested and if appropriate for this project. Thanks.

**Comment by drc007** [comment]
Hi,

I’d be happy to contribute, I’m based in the UK and I’m already working on a couple of WT funded projects.

Cheers


Chris

**Comment by MedChemProf** [comment]
Great! I suggest we see who else is interested and then schedule something like a Google Hangout to discuss further. Let me know what you think.

**Comment by drc007** [comment]
I gave a talk at the Cambridge Cheminformatics Network about the work that had been done to make the OSM data more accessible and there were a couple of people who asked if they might be able to contribute. I'll forward this to them and see if they have time.

**Comment by alintheopen** [comment]
Great all round. I'm happy to work on a proposal with you Chase. @ErinSheridan and the students are coming to visit the school today and I'm going to talk to them more about their research challenge, so I'll be able to talk with @ErinSheridan today.

**Comment by alintheopen** [comment]
Closing this issue and moving discussion to #374.
