### ISSUE TITLE
18-crown-6 Quantity

### ISSUE THREAD

**Issue by ThomasYork20** [OpenSourceMalaria/OSM_To_Do_List#340]
In the latest molecules of the Triazolopyrazine Series as synthesised by first year TSP students there was variation in the quantity of 18-crown-6 used. A ChemDraw file detailing reactant quantities claimed a 0.7 equiv for 18-crown-6 for a nucleophilic aromatic substitution. Prior similiar synthesises such as AEW246-1 uses a tenth of the 18-crown-6 quantity (0.07 equiv). What are the expected variations in final product with this variation in reagent? @alintheopen @mattodd 

http://malaria.ourexperiment.org/triazolopyrazine_se/8425/Synthesis_of_3naphthalen2yl5phenethoxy124triazolo43apyrazine_TY41.html
http://malaria.ourexperiment.org/triazolopyrazine_se/9715/Synthesis_of_tertbutyl_352phenyl2tetrahydro2Hpyran2yloxyethoxy124triazolo43apyrazin3ylpiperidine1carboxylate_AEW_2461.html

**Comment by drc007** [comment]
I suspect that 18-crown-6 is only needed in catalytic quantities so it should not really impact on yield.

I may be that on a small scale higher equiv were used to simply help weighing out small quantities.

**Comment by mattodd** [comment]
Agreed. A week in the lab will save you an hour in the library - what yield did you get?

**Comment by alintheopen** [comment]
we don't know yields yet - we'll find out next time on...TSPs do OSM :)
BUT, TLCs say everything is OK. 0.07 equiv. is the usual amount but 0.7
should be fine.

**Comment by mattodd** [comment]
Hey @ThomasYork20 - so did this matter? What was your conclusion, and have you written that up in the ELN? Could we close out this Issue now, or are you still investigating?

**Comment by ThomasYork20** [comment]
Hey @mattodd it didn't seem to matter in the end. Chris was right in that variation in the quantity of the catalyst didn't seem to affect the yield (50%) and subsequent H NMR analysis has shown the product produced to be the desired one. So, happy ending, the issue can be closed.
If anyone wants to view the experiment and results it can be found here.
http://malaria.ourexperiment.org/triazolopyrazine_se/8425/Synthesis_of_3naphthalen2yl5phenethoxy124triazolo43apyrazine_TY41.html
Thanks Chris and others for advice.

**Comment by MedChemProf** [comment]
It may be my unfamiliarity with the LabTrove notebook, but I am having difficulty determining which of the reactions in the Triazolopyrazine Series notebook worked and which did not. Some of the experiments provide TLC and NMR data, but many do not. Quite often there is also no yield or final amount listed. Please let me know if I am missing something basic. Thank you in advance.

**Comment by mattodd** [comment]
Thanks for pointing this out. No, you're not missing anything. This is up to the author-researcher. Personally I strongly encourage everyone to install a conclusions statement up the top of the reaction when it's finished, since every experiment needs a conclusion - see Point 2 in the [ELN guide](http://malaria.ourexperiment.org/osm_logos_and_templ/8576). Without that we're left with vagueness or having to dig through the detail to work out what happened. If you see missing conclusions, please don't hesitate to call people out on those entries. The commenting function in Labtrove doesn't work well, so you could always start an Issue here on Github for offending entries or groups of entries.

**Comment by alintheopen** [comment]
Hi Chase, Thanks for flagging. I will add some conclusions statements
today, haven't done so for the last little while, but yes it certainly
helps. I have been wrangling with some purification problems for the last
few reactions but will hopefully work out whether I have pure product or
stuff for the organic waste very soon :)

One idea that I have also thought about trialling is a 'living'
experimental file. This would be a G doc whereby once a chemist is happy
with a procedure and has collected full characterisation data they can
write up a paper style experimental and link to the 'perfect' entry in the
ELN. We could use a spreadsheet to track this and of course continue to add
compounds to the master compound sheet so that collating experimental for
upcoming publications is even easier.

**Comment by MedChemProf** [comment]
Alice, that sounds great and thank you. The reason that I was digging into the experimentals is that I am trying to plan out a set of reactions and targets for an upcoming group of students. Next semester I will have a group of 8 in a lab based medchem research elective. I wanted to assign targets to each of the students that would contribute to the OSM project. Beyond those 8, I will have another 4 students in what is known as an experiential rotation. Each one of the experiential students will be working full time for a 6 week period in the lab. All of the students are excited to start.

Might it be possible to schedule a Google Hangouts meeting so I could pick your brain on your experience with the triazolopyrazine core? I would also like to get your thoughts on some relevant targets versus what I think the students are capable of synthesizing. I also need to put in for a chemical order in the next few weeks in preparation of the student start date.

**Comment by alintheopen** [comment]
Hi Chase, Of course. I can do any day except Wed next week - quite flexible
with time too. Cheers Alice

**Comment by mattodd** [comment]
Sounds perfect, let's suggest some times. Again 9:30am Sydney time one day? Can do any day except Tue. Could we then start a new GitHub Issue with the times, and start sketching some suggestions (something we need to do in any case) so that we can close out this issue on 18-crown-6!

**Comment by alintheopen** [comment]
Closing and opening new thread #352.
