### ISSUE TITLE
Adding Liver Stage Potency to the Master Sheet

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#346]
Hi @jhon4903 - got time for a little bit of data entry? 

Three molecules from Series 1 have data on their potency vs. the liver stage of the parasite. All the data are on [this page](http://malaria.ourexperiment.org/biological_data/8227). There are **two** values each for OSM-S-5 and OSM-S-38, and one page (linked therein) back to a value for OSM-S-111.

Could you check that these compounds (all "Series 1") are actually in the Master Sheet, along with all their strings (if not, add), and then put in the liver stage potencies in column P in micromolar? (compound OSM-S-38 is pretty amazing by the way)

Could you also add the cytoxocity value to column Q "HepG2" - OSM-S-5 is I think 9.8 and 18, OSM-S-38 is >50 and OSM-S-111 is 4.4 - could you check that these are right?

Reply below when you're all done or if you've questions. Thank you!

**Comment by jhon4903** [comment]
@mattodd I have just finished adding the parasite (IC50) and cytotoxicity (HepG2 IC50) values for all three compounds. A couple of things to comment on include;
- Only finding one value for the potency vs. the liver stage of the parasite for OSM-S-111 (0.3454 uM)
- Duplicates of OSM-S-38 (number 105 & 106 on the mastersheet). I have added the values to both rows in case you would like to delete one of them.
- OSM-S-111 was added, including the strings but there seems to be two different InChI in the links I have found below:
1. https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/60
2. http://malaria.ourexperiment.org/osm_procedures/7194/Preparation_of_OSMS111.html

I have added the InChI from the second link since it seems to match OSM-S-111 from the link I got in the original post. Please let me know if this is incorrect. 
- One last thing to comment on is the ID for OSM-S-111, I have added the ID from the excel file for the data on OSM-S-106 and OSM-S-111 in the column, MMV project code: MMV 11/0040 but not sure if this is correct since it shares the same code as OSM-S-106, could you please verify?

Thank you.

**Comment by drc007** [comment]
Hi,
It would be best to delete one of the rows for OSM-S-38.

Also @mattodd out of curiosity how was the stereochemistry of the double bonds defined?

**Comment by mattodd** [comment]
Thanks @jhon4903 

1) Code for OSM-S-111 - I'm not sure it has one, which we will have to fix up at some point. The code you (perfectly reasonably) used is for the project code, not for the compound.
2) Yes, there's only one value for OSM-S-111
3) Duplicate of OSM-S-38 - looks like this has already been deleted? Fine if so.
4) OSM-S-111 Inchi. Well spotted. Not sure what that means. I get

InChI=1S/C24H22N2O2S/c1-16-13-19(17(2)26(16)20-9-11-21(28-3)12-10-20)15-22-24(27)25-23(29-22)14-18-7-5-4-6-8-18/h4-15H,1-3H3,(H,25,27)/b22-15-,23-14-

which is different again. The ELN entry is correct, I think, but the #60 is wrong, and I've corrected it. I imagine the InChI will depend on the E/Z geom of the imine, right? Which is not terribly important. @drc007 Crystallography on OSM-S-35, OSM-S-42, OSM-S-54 and OSM-S-9 established geometry of the C=C double bond, and is assumed series-wide as a result. Data are collated in the paper that's nearly ready on Series 1 - should all be in the ELNs, but might be hard to find...

I added in some potency values for OSM-S-38 and OSM-S-111 while I was at it.
