### ISSUE TITLE
Completion of OSM Series 1 Online Dataset

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#354]
Today we received the green light from MMV to submit Paper 1, which is really exciting. There are just a few loose ends.

So, the Datatset. I think we’ve finished adding all the data we have for Series 1 to the [Master Sheet](http://tinyurl.com/OSM-Compounds), meaning we can take a snapshot of the Series 1 data for offline submission along with the Series 1 Paper, and we can use @lpatiny ’s [link and method](https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/348#issuecomment-148936896) for readers to find the “live” dataset as per #348 . This is a crucial part of the paper.

Questions about some recent changes in the Master Sheet:

1) Handling “zero” activity is still a problem since people describe this in different ways. Sometimes inactivity is “nd” (e.g. cell L97) or zero (e.g. cell L129), or sometimes it’s a very high concentration (e.g. cell L53) or some descriptive statement (e.g. cell L138). In some cases there are qualifiers (e.g. “>5”, e.g. cell I111) which seems to need a new column. In some cases there was a practical problem like low solubility (e.g. cell L82) I wonder how we deal with this, routinely. I’m almost tempted to have a special value/symbol for “no good, don’t even worry about the exact value”.

2) How should we handle multiple results from the same assay? At the moment I have the values in one cell separated by a comma (e.g. cell I89)

3) We are at the moment not correlating data points to specific runs of an assay. As I mentioned before this is *probably* OK, but we do now have quite a few instances of the Avery assay (see cell J13 in the [Assays Sheet](https://docs.google.com/spreadsheets/d/1CyF9O1zu46I-l2eRgRtMK8oBZRJV2um0482j17aVIC4/edit#gid=0)) and I wonder if we should try to be more granular.

4) I’m including chemist synonyms in the ID column (B) of the Master Sheet. Any problems with this? At the moment the values are separated by semicolons. OK, or should those be commas? I have removed spaces from these synonyms (e.g. ZYH 11 or ZYH-11 has become ZYH11). I presume spaces are a pain in synonyms, generally, and we ought to avoid them, or at the very least replace with hyphens (even though @cdsouthan doesn't like them...).

Any other issues with the data for Series 1? I think all the biological data are now in the Master Sheet.

**Comment by cdsouthan** [comment]
Good to see this progressing.  I can pick up some general and specific issues - but none of this should slow things down. The basic challenge as I see it is harmonisation and synching between different but equally important instaciations viz   a) the paper (static snapshot b) the mastersheet  (dynamic)  and c) data relationships specific to the paper surfaced in databases (should be dynamic but refresh/replace often not done). Note that the most important forks for c) are ChEMBL and PubChem BioAssay and whatever future extractions from the paper may happen, for example  if ChEMBL extracts this paper (even SciFinder - but they probably won't iterate with the likes of us)

**Comment by mattodd** [comment]
Inactivity vs. low activity - happy to report the raw details in the master sheet, so long as those values (which have a range of forms) are understandable to the system that is used to visualize the data, or any secondary system that might take the data and do something with them. @madgpap  do you have to annotate “inactive” manually before import into ChEMBL, for this  reason that there can be diverse input types?

Multiple values: we already have one row per compound, and one column for each assay. If there are then multiple values they are at the moment separated by a comma within the one cell. Is this typical/useful/acceptable?

Referee Hat Points: a) Don’t know, but this is perhaps an example of why you don’t put too much faith in one assay result. There are not too many of those examples. b) error ranges - these are/are not as quoted by the people doing the assays. c) Rounding - for the paper I’d agree. Data are entered as received. d) controls are essentially always included - they are shown in the raw data and mentioned in the paper, etc.

We’ll try to maintain consistency, aware that results are incorporated into Google results in a few hours. I think we need to be sure, as a community, just to avoid spaces.

Yes, IUPACs dropped from master sheet. Is there a point in those being there given that we have the strings?

Pubchem CIDs - if this is a manual operation, then why do it now? Won’t these ultimately be generated automatically, later, once we ensure the dataset is public?

Cross-checking the strings: want to volunteer doing that if we post a sheet for Series 1 somewhere as it stands?

**Comment by madgpap** [comment]
Multiple values in a single cell is fine but I would replace comma with semicolon as it former might confuse a csv export. 

Wrt Chembl, we do standardise activity types and units (see Papadatos et al 2015) but we don't bin into actives and inactives. 

George

**Comment by cdsouthan** [comment]
Inactivity - thats fine but I dont see what most analysists can do with the diffent report types under the concept of  "activity not recorded at thresholds used for this assay" . Since we are SAR tracking I cant see it makes much difference if the threshold is 5 or 10 uM (but recording experimental solubility or lack therof  is very important but could be recorded as a seperate parameter)

Multiple values for identical assay conditions:  w b better if the experimentalists could avoid this, use a mean? or repeat (3rd point) and average?  Sure, the paper and ChEMBL can cope with the ; but pragamtically SAR analysis cannot (can check how PubChem BioAssay will cope

Referee hat:  OK lets see if  any official refereee picks up on it (although we have openly primed them here which is an interesting precedent!). As ever, unless the experimental variance of the bioactivity measurments are defined to some extent  (e.g. inter-team concordance as surrogate for intra-team concordance)  we are left with jellyfish-like SAR 

Consitancy e.g. no spaces and minimal hyphenation - we concur

I can concatenate these last three points.  JFTR I'll go for council of perfection here as the most usefuk thing I can do (perhaps over-presciptive but you are doing fine and are free to ignore it of course) but here goes

1)  I'm not an expert on the many causes of round-tripping divergence but we have to adapt to it and the bigger your series the worse it can get (but the majority are probably OK).  This is why I suggest double belt-n-braces (i.e. SD, SMILES, InChI string and Key, plus IUPAC) as the "holy heptet" of all robust registration systems.   

2) Sounds like a cop-out I know but your primary consistancy checking IMCO has to be baked in as core operation by your chemistry teams from start (design) to finish (analytical data for the synthesis batch and consistancy checking the holy heptet)  For better or worse, Chemdraw remains central to OSMs execution of this. AYK I gladly do secondary

**Comment by mattodd** [comment]
Three points as we move to finalise the dataset:

1) In the [Master Sheet](http://tinyurl.com/OSM-Compounds) I have manually added "50" (micromolar) for compounds we should consider inactive. I've done this only for Series 1 at the moment (145 compounds). This should make it easier for @lpatiny 's visualisation of the series to use the mean potency value in column T to provide some interest for this series, in terms of allowing browsing of the approximate potency vs other features of the molecules. Manually doing this is suboptimal, and it's a fictional value, but what can you do. 

2) Replaced commas with semicolons as per advice from @madgpap where there are multiple values in one cell. This too is only for Series 1 at the moment.

3) @cdsouthan I didn't understand your point in the previous comment. Are you saying that we ought to be proactively putting in other synonyms (like CIDs) into column C?

**Comment by cdsouthan** [comment]
Attached is the CID mapping of  105 of the 145. These could go in to column C (not in order but maybe your local Excell wiz  can do the colunm joins with csvfix or something similar).  However only 96 came up with live links   http://www.ncbi.nlm.nih.gov/sites/myncbi/christopher.southan.1/collections/49117173/public/

[Series 1 only 18  nov InChIs to CIDs.xlsx](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/38350/Series.1.only.18.nov.InChIs.to.CIDs.xlsx)

**Comment by mattodd** [comment]
That's great, Chris, thanks. Anyone know how to port these most efficiently into the [Master Sheet](http://tinyurl.com/OSM-Compounds)?
This is a new, rather specific, synonym. Should it not have its own column?

**Comment by drc007** [comment]
I’d put it into a new column, we then use it to create a URL that people can use to search.

Chris

**Comment by cdsouthan** [comment]
Yes - and the url would be https://pubchem.ncbi.nlm.nih.gov/compound/xxxxxxx   
These links would be useful for the MS (as would other live-links) but not sure if the publisher could make live.  For the future would be good to get  all 145 into PubChem (as said  before) via BioAssay submission.  JFTR the mapping was done with  https://pubchem.ncbi.nlm.nih.gov/idexchange/idexchange-help.html. As ever there seemed to be a bit of noise between Keys and Strings

Since its part of my role to be pedantic  - we need to be careful with the term "synonym"  e.g. since the CID is the primary ID for a defined PubChem structure its not technically generated as a synonym even if we consider it such semantically.  Thus OSM and MMV numbers can be synonyms in that CID record but only if they are submited by "someone" who thus provenances the name-to-struc (n2s).  Arguably the OSMs are "your" primary IDs i.e. not synonyms, when your team de-novo designer locks that  OSM ID to a Qintet (as MMVs I assume are primary IDs in Geneva).  Note that ChEMBL will generate thier own primary ID for the structures you submit to them (or they pull from you) and names/synonyms you link/provenance in that step.  ChEMBL then becomes a submitter to PubChem in turn where their primary ID is mapped into the CID via "their" SIDs.  The synonyms are thus transitively passed into the CID record and heuristically ranked.   This is arcane stuff but appreciating it can at least help ameliorate the global  proliferation of n2s/activity/ ID x-mapping spaghetti.  

Here endeth the lesson according to Christopher :)

**Comment by mattodd** [comment]
Hi @cdsouthan the CIDs for Series 1 are now in the Master Sheet. Column C. Light red shading = those compounds you reported as lacking CIDs. There are 4 compounds in the Master Sheet not in your spreadsheet - those with heavy red fill. These had no InChIKeys, or, in the case of OSM-S-88, an InChI where a Key should have been. For these four would you mind repeating your analysis to retrieve Pubchem CIDs?

**Comment by mattodd** [comment]
LAST CALL on the [Master Sheet](http://tinyurl.com/OSM-Compounds) before I take a snapshot for paper submission. @cdsouthan any more in the Pubchem CIDs I mentioned in the above post, or are we done, do you think? Does anyone have any other problems with the data - just for Series 1? Ready to go? I'll also be including a tab for the [Assays Sheet](https://docs.google.com/spreadsheets/d/1CyF9O1zu46I-l2eRgRtMK8oBZRJV2um0482j17aVIC4/edit#gid=0) in the snapshot Excel file so that people have a decent understanding of the column headings. Once we're done I'll be generating the SDF as per @lpatiny instructions in #349

**Comment by cdsouthan** [comment]
From the top
OSM-S-284 =  CID  9794037  N-methyl-N-benzylglycinamide 
OSM-S-284 =  CID  151411  2-(methylamino)acetamide
OSM-S-284 =  CID  939880  2-Phenylamino-thiazol-4-one

**Comment by mattodd** [comment]
Thank you @cdsouthan . The intermediates you mention are there for completeness - they weren't biologically evaluated. You have two OSM-S-140's in the above?

**Comment by cdsouthan** [comment]
Fixed (many eyes on data sheets is good) 
n.b. for the sake of a few assays should screen all intermediates with shared substuctures to products  YJNK.

**Comment by mattodd** [comment]
Paper submitted along with snapshot of datasheet and link to live version, so closing.
