### ISSUE TITLE
Literature Survey

### ISSUE THREAD

**Issue by alintheopen** [OpenSourceMalaria/OSM_To_Do_List#357]
@tscmacdonald to perform a literature survey and determine:
1. Best synthetic routes to Daraprim
2. Possible routes with UG/High School 'friendly' reagents
3. Analogs tested against toxoplasmosis, malaria and any other indications
4. SAR

**Comment by alintheopen** [comment]
@tscmacdonald will use LabArchives as his ELN to begin with as this is used with UG classes at USyd. All data will ultimately be placed in the open. All student notebooks will be completely open. @tscmacdonald please could you summarise your findings here on GitHub and detail any important literature references.

**Comment by tscmacdonald** [comment]
OK, here's a basic overview of the least offensive historical synthesis I could find:

![scheme](https://cloud.githubusercontent.com/assets/6529539/11023145/915a0366-86c4-11e5-8241-667ee7c2a07d.png)

Three steps, no column purifications. There's what looks like a slightly tedious work-up after step one, and no purification at all going from 2 to the final cyclisation (just removing the remaining orthoester under vacuum, which from my experience might take a while).

The downside: we're using metallic sodium to make sodium ethoxide in 2 of the 3 steps (to enable the condensation in step one, then to deprotonate the guanidine.HCl in step 3). The only alternatives I've seen are NaH and LDA, which hardly seems friendlier. I'll have a think about possible alternatives (maybe we can try hydroxides + crown ethers again?), but the relevant pKas are quite high.
 
Original paper, using diazomethane: doi:10.1021/ja01152a060 (first step is fine)
Replacing diazomethane with the far friendlier alkyl orthoesters: doi:10.1021/ja01125a049

**Comment by mattodd** [comment]
OK - but you're planning to trial some of this chemistry, right? I guess we have two choices, ultimately, which is to go with harsh conditions and manage the challenge of those moments, or we use the project to investigate milder/nicer/more efficient ways of achieving the same result.

Obvious question: the procedure that is used at the moment to make the compound on a large scale. I don't suppose there's a way to find out whether it's the same as the one in the patent? There are no more recent patented approaches, right?

**Comment by tscmacdonald** [comment]
Trialling the chemistry should start on Friday, if the SM has arrived. The least harsh alternative chemistry I've found uses tBuOK in THF at rt and reasonably short reaction times, which (if it works) would be more manageable. The guanidine freebase for pyrimidine formation is the other big issue: from what I've read, guanidine needs to be made fresh (from the HCl salt, using an ethoxide) and forms the carbonate from CO2 in air quite quickly. All of this should become more clear once we've actually run a few reactions.

I haven't been able to find any substantially different reactions schemes, from the drug's discovery in the 1950s up until recent patents. The only substantive variant uses diazomethane to make the enol ether (?), rather than orthoesters: apparently the diazomethane reaction is cleaner and more reliable, but probably isn't something we want first years playing with.

**Comment by MedChemProf** [comment]
You most likely have seen some of the references I listed below, but I came across them while looking for synthetic routes to some analogs of Daraprim.  J. Med. Chem. 2006, 49, 2568-2578 shows an experimental for the condensation of an acid chloride and phenylacetonitrile using Et3N / DMAP as the base. This might be an alternative to the sodium ethoxide first step. The same reference also describes the use of trimethylsilyldiazomethane instead of diazomethane for the enol ether formation. Safer than diazomethane, but a step you would want an experienced chemist running versus a novice. A much more recent paper (J. Med. Chem. 2015, 58, 4483−4493) shows the use of dimethylsulfate and K2CO3 to form the enol ether. They reference back to a J.Chem. Soc. Perkin Trans 1 paper that I have not yet received from the interlibrary loan.

**Comment by ErinSheridan** [comment]
From my perspective, we'd be happy to trial some of the milder conditions.  I can always handle the chemicals/procedures that I don't think are safe for high school students, but it's obviously better when the  students can do it themselves.   Either the acid chloride reaction (10.1021/jm0510934) or the potassium t-butoxide (10.1016/j.tet.2013.10.007) look like reasonable options for us to try for the acyl condensation.

We're still waiting on the starting material too, and we would have to wait for the acid chloride/tBuOK as well.

**Comment by drc007** [comment]
Is using sodium a major issue, I remember using sodium, potassium and phosphorus at school but then I am rather old! You can buy sodium ethoxide, in my experience it does not keep once opened but a fresh bottle should be fine.

**Comment by drc007** [comment]
I'd suggest avoiding dimethyl sulphate, very toxic.

**Comment by ErinSheridan** [comment]
We still use Na (and sometimes K) for demonstrations, but the students can't use them.  So if we went with that, I would have to do that part - which is ok of course, but not ideal.  The advantage of the sodium route for us is that we already have sodium (in fact we even have an unopened, quite new looking bottle of sodium methoxide).  

If the starting material turns up by Friday then maybe we can try the reaction using the sodium methoxide.

**Comment by drc007** [comment]
Certainly worth a try.

**Comment by alintheopen** [comment]
@tscmacdonald and I have time to trial a few things but milder bases probably won't work in the reaction described so we may have to settle for tBuOK or methoxide and decide how to safely run these experiments at Syd Grammar. Certainly won't be using dimethyl sulfate though!  Alternatively, maybe we should think about a different route to the target? We are also hoping SM is here by Friday but will try with phenylacetonitrile if Sigma don't deliver.

**Comment by MFernflower** [comment]
Diffrent class of compounds but is shown to be very effective against toxo:

http://www.ncbi.nlm.nih.gov/pubmed/15270113﻿

**Comment by MFernflower** [comment]
Unrelated compound, But I have seen it being thrown around on toxo tests:

![diclazuril](https://cloud.githubusercontent.com/assets/3164942/11110332/6eb09220-88c8-11e5-8d25-f3e67f06c00d.PNG)

Any ideas on possible MOA (perhaps it sheds electrons in a similar fashion to flagyl?)

**Comment by MFernflower** [comment]
Regaruding SAR: Daraprim is nothing more than a antifolate - Could someone work on less toxic derivatives of methotrexate?

**Comment by MedChemProf** [comment]
@tscmacdonald @ErinSheridan @alintheopen I was just re-starting this discussion to follow up on the topic of 'Mentors' for some of the junior chemists. I have several industrial medicinal chemists interested in mentoring chemistry students and providing feedback on their experimental work. If anyone has students recording their experiments in a Labarchives ELN, please let me know if you have students or know of any students willing to have a mentor. I will then need the url of the open Labarchives ELN so I can point the industrial medchemists in that direction. Thanks.

**Comment by mattodd** [comment]
This is great, Chase. Important and useful to have mentors for student lab books. Labarchives is our best bet for this at the moment, because Labtrove has no alert mechanism for comments. But I suppose any student working in this area on any open lab notebook would also work, provided commenting is easy. The point here is to make sure that the dialogue is effective for student and mentor and that the mentor doesn't have to spend a long time figuring out how the system works?

**Comment by ErinSheridan** [comment]
We're back at school, and the students are extremely eager to begin some reactions!  Theoretically we could start tomorrow afternoon, though I can see from @tscmacdonald 's [summary](http://malaria.ourexperiment.org/daraprim_synthesis/13962/Pyrimethamine_synthesis_Status_at_end_of_2015.html) that using methoxide for the first step didn't work.  We can proceed with the KtOBu, but there would be (another) delay since we don't have any at school.  So in the interest of letting the students have a go, I think we might give the methoxide another go, maybe with a longer reaction time.

And we would love to have a help from a mentor, that sounds fantastic.  I had a look at Labarchives today, it seems easy enough to use instead of Labtrove if this is the best way.

**Comment by alintheopen** [comment]
Hi Erin, sounds like a good plan to let the students have a go to and then
we can see what we can do about either expediting the delivery of a new
base or providing you with some slightly more advanced material.

If you guys continue to use Labtrove that is fine, not entirely sure if you
would be able to use labarchives without an institutional login. Will be in
touch later this week re. mentor, plans for this semester a little later
this week.

Cheers

Alice

**Comment by mattodd** [comment]
Great! I can't comment on the most promising route for the chemistry (Tom?)
but Labarchives is fine from our perspective - any ELN that can be made
open and allows raw data deposition as well as commenting. Erin do I take
it that you are able to use a free account, and then make that openly
available? If not I wonder if we can, here at the Uni, make the lab book
and then share access with you as a collaborator. Best method here,
Labarchives users?

On 1 February 2016 at 15:16, ErinSheridan <notifications@github.com> wrote:

> We're back at school, and the students are extremely eager to begin some
> reactions! Theoretically we could start tomorrow afternoon, though I can
> see from @tscmacdonald <https://github.com/tscmacdonald> 's summary
> <http://malaria.ourexperiment.org/daraprim_synthesis/13962/Pyrimethamine_synthesis_Status_at_end_of_2015.html>
> that using methoxide for the first step didn't work. We can proceed with
> the KtOBu, but there would be (another) delay since we don't have any at
> school. So in the interest of letting the students have a go, I think we
> might give the methoxide another go, maybe with a longer reaction time.
>
> And we would love to have a help from a mentor, that sounds fantastic. I
> had a look at Labarchives today, it seems easy enough to use instead of
> Labtrove if this is the best way.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/357#issuecomment-177754581>
> .
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by alintheopen** [comment]
@tscmacdonald has written a nice summary [here](http://malaria.ourexperiment.org/daraprim_synthesis/13962/Pyrimethamine_synthesis_Status_at_end_of_2015.html):

I don't think there is necessarily a huge advantage in swopping from Labtrove. @MedChemProf's team are using LabArchives as that's the ELN purchased by their Uni (as is the case with The University of Sydney).

**Comment by ErinSheridan** [comment]
I didn't originally try to set up an account for labarchives, I had a look at the information about how it works.  I've checked and Alice is right, it looks like I would need a university email address.  In that case, at least I already know how to use Labtrove!

**Comment by MFernflower** [comment]
@alintheopen - This is a bit unrelated - But I'd like to compliment you on how easy to read your synthesis schemes! - I know next to nothing about synthesis and I was still able to understand how you made some of the series four drugs! I also moved all my proposed molecules/ideas to a github repository that can easily be downloaded.

**Comment by MedChemProf** [comment]
@ErinSheridan @mattodd @alintheopen I have ended up purchasing one seat of the Professional Edition of LabArchives and 12 Student seats at a reduced price. I then add each student via their school email address. 12 students is the most that I can have at any given time, but I can have more than 12 over the year by switching a student from 'User' to 'Guest' as they rotate out of the lab. I can then add a new student to the open seat. I have been happy with LabArchives, but it is not an ideal medicinal chemistry lab notebook.

**Comment by alintheopen** [comment]
Hi @ErinSheridan. Are you free for a telephone catch up/google hangout this week? Cheers

Alice

**Comment by ErinSheridan** [comment]
@alintheopen my apologies for missing this!  I must have not seen the email notification somehow.  
I'm free tomorrow between 1pm and 3pm, or after 5pm, or else on Thursday after 3pm.

**Comment by MedChemProf** [comment]
@alintheopen @mattodd I am not sure where the original thread on this topic resides, but I wanted to follow up with a response that I just received from LabArchives. Previously I mentioned that I discovered that if you paste a SMILES string into the Search window within LabArchives, it would not find the target SMILES. I reported the bug and LabArchives stated that they would add it to their queue. As a work around, they did tell me that "It turns out our Search Feature will in fact search for Smiles text strings provided that the search is in quotes." This does seem to work if you need to do this in the short term. As was reported by @cdsouthan , if your notebook is open, it does eventually get indexed and can be found with a Google search.

**Comment by alintheopen** [comment]
Thanks @MedChemProf. I'm closing this issue now to start a new Daraprim thread at #374
