### ISSUE TITLE
Cubane?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#379]
I was speaking with Craig Williams at UQ yesterday about his [lovely cubane work](http://onlinelibrary.wiley.com/doi/10.1002/anie.201510675/abstract), which largely validates cubane as a bioisostere of phenyl, and one with potentially lower metabolic liability. Surely we could incorporate this in the side chains of Series 4, given that we might be able to obtain derivatised cubane (e.g. the carboxylic acid) from CSIRO here in Aus.

One could imagine a number of ways of doing this, e.g. the most obvious

![cubane possib](https://cloud.githubusercontent.com/assets/4386101/14479409/7b1a4d8c-0161-11e6-8f62-504006c1acf2.jpg)

But there may be others. The replacement certainly helps with deplanarisation. What say you all?

**Comment by MedChemProf** [comment]
@mattodd Interesting idea and I think worth trying beyond just as a proof of concept with regards to the maintenance of activity. I have convinced myself that the primary metabolic hotspot is the pyrazine ring of the triazolopyrazine core and not necessarily the tethered ethoxyphenyl side chain of the various analogs that have been synthesized. Testing your proposed analog (whether active or not) for metabolic stability might definitively inform us whether or not the liability is the core itself versus the side chain.

**Comment by MFernflower** [comment]
While on the topic of unusual functional groups in drugs - Could replacing the difluromethoxy group with a TMS be in order?

**Comment by drc007** [comment]
TMS ethers of phenols are pretty labile.

Chris

**Comment by MFernflower** [comment]
Woops! I ment to say that replacing the entire OCHF2 group with TMS.

**Comment by mattodd** [comment]
But why, Mandrake? If you suggest an alternative, it helps everyone if you
can provide a Why. Is there a reason why you think this might be
advantageous, based on what's known in the literature? Is it likely such a
replacement would solve a problem we currently face, i.e. improving
potency, improving solubility and/or slowing metabolic clearance? The
cubane replacement does seem to have such advantages, which is the reason I
suggested it. What might a TMS switch solve that means this suggestion
should be prioritised over others? If there are reasons (and there may well
be) do you have in mind a lab with experience in making such compounds that
might be interested in making your compound, or do you have a way to
contact any local NY students with the bandwidth to do so?

On 19 April 2016 at 05:01, MFernflower <notifications@github.com> wrote:

> Woops! I ment to say that replacing the entire OCHF2 group with TMS.
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/379#issuecomment-211530601>
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by MFernflower** [comment]
You have quite valid points indeed! I will attempt to explain my current understanding and ideas around this class of molecules:

1. The TMS group - In retrospect this was not a good idea at all as silicon compounds are often hard to produce and purify - It also seems that organosilicon drugs can be quite random with regards to pharmacokinetics. I feel that my pushing of silicon-based compounds may have been due to personal interest in organosilicon drugs rather than collective interest and thus I will not propose anymore silicon bearing derivatives. However this still leaves a open question - is an oxygen bearing functional group needed on the right phenyl ring? I don't think it is needed as looking into the openwetware page reveals that compounds with a cyano group replacing the DFM have been tested and found to be slightly less or as potent as there brethren - Perhaps taking a known good S4 ether and replacing the DMF group with a CF3 would be a good way to confirm or deny if this is a required aspect of S4 SAR.

2. Replacing the ring on the end of the ether linker with pyridine appears to give a massive reduction in logp. Metabolic stability is still a major problem however I feel this is a inherent issue with the core itself (as chase had talked about above)  - however if the aforementioned cubane does prove to solve many of these problems - than the pyridines are totally null and void 

3.  Regarding synthesis and collaboration efforts - I had asked a local university if they were willing to produce and test novel compounds and they stated that they cannot produce anything more than a few basic molecules at a time as they are not a licensed research facility and funding is very tight. I have enrolled in a program with my local aquarium/biology research facility - While this program is more biology orientated - The directors do know a few chemists and do have contact with undergrad students - Perhaps I could partner with an undergrad who is looking for a project.

**Comment by mattodd** [comment]
Chemdraw gives CLogP of the cubane analog as 4.7. I wonder if that's accurate. I had thought that deplanarisation would help, but perhaps I'm confusing lipophilicity with kinetic solubility. Grease is grease. I might see if Craig himself is interested in the synthesis of this molecule, or at least the cubane alcohol subunit.

**Comment by drc007** [comment]
Chemaxon gives logP 3.5
XlogP gives 3.8
OChem 2.3
alogP 1.9

The variability would suggest this sort of structure is outside the applicability domain of the algorithms

**Comment by madgpap** [comment]
+1

**Comment by drc007** [comment]
One of the features of the two aryl systems is that there is the possibility of hydrophobic collapse with the two aryl rings pi-stacking (this was seen in the NMR). It would be interesting to see how the proposed cubane behaves.

**Comment by mattodd** [comment]
I should have checked - in the paper logP values are indirectly calculated from a combination of lit values (of benzene analogs) and HPLC retention times (of the benzene vs cubane analogs). This is described in the [SI](http://api.onlinelibrary.wiley.com/asset/v1/doi/10.1002%2Fanie.201510675/asset/supinfo%2Fanie201510675-sup-0001-misc_information.pdf?l=SkaBT8QEx2qMKFzmpntImmI8cjaKB4bINg6QI4pKbitgJKIE3mgTjzVbUP31CZn0TCzf7Vgwto%2FG%0AJvmDCQpFiiJ0BCWngR1ozycIogbuDnloicjL6%2BJo9w%3D%3D). The results suggest cubanes have similar logP values, but the effect in our case may be different, of course.

**Comment by MFernflower** [comment]
Shouldn't the cubane be replacing the benzene ring on the right-most side of the molecule? The aryl on the ether linker is quite easy to replace with something a little more common (furan, benzonitrile, imidazole, ETC)  as it is thought that whatever is on the linker side does not really matter (hence the creation of a sulfoxide linker by Edwin)

**Comment by mattodd** [comment]
Certainly that's a possibility, yes. We'd need cubane aldehyde, which might
be available. Though unsubstituted phenyl is no good in the northeast, so
we'd need "para" substituted cubane aldehyde most likely.

**Comment by MFernflower** [comment]
That does raise a good point - how would you bolt the difluoromethoxy onto the cubane?

**Comment by mattodd** [comment]
Oh, I'm not sure it's worth the extra synthetic hassle of doing that at
this stage. We know that 4-Cl and 4-CN etc work fine on phenyl, so we can
go with one of those rather. It depends on what's synthetically accessible.

On 30 April 2016 at 10:15, MFernflower <notifications@github.com> wrote:

> That does raise a good point - how would you bolt the difluoromethoxy onto
> the cubane?
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/379#issuecomment-215912886>
>



-- 
MATTHEW TODD | Associate Professor
School of Chemistry | Faculty of Science

THE UNIVERSITY OF SYDNEY
Rm 519, F11 | The University of Sydney | NSW | 2006
T +61 2 9351 2180  | F +61 2 9351 3329  | M +61 415 274104
E matthew.todd@sydney.edu.au | W
http://sydney.edu.au/science/people/matthew.todd.php
W http://opensourcemalaria.org/ | W http://opensourcetb.org/ | W
http://opensourcepharma.net/

CRICOS 00026A
This email plus any attachments to it are confidential. Any unauthorised
use is strictly prohibited. If you receive this email in error, please
delete it and any attachments.

**Comment by MFernflower** [comment]
I understand fully.. I also did not know that 4-chloro was an acceptable modification to the rightmost side! I'll keep that in mind when doing computations - I also just got a Linux laptop so this should make my computations a bit easier and possibly more detailed! Oh, by the way what did you think of the imidazolyl on my example molecule? Have 5 membered rings on the linker end been tested at all?

**Comment by MFernflower** [comment]
@mattodd I understand completely.. I also did not know that 4-chloro was an acceptable modification to the rightmost side! I'll keep that in mind when doing computations as it makes a few things slightly easier - I also just got a Linux laptop so this should allow me to do more detailed computations and whatnot. Also what did you think of the imidazolyl on my example molecule? Have 5 membered rings on the linker end been tested at all?

**Comment by mattodd** [comment]
Hi Mandrake, you can browse the [wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series) or the [spreadsheet](http://tinyurl.com/OSM-Compounds) for all the structure-activity data.

**Comment by MFernflower** [comment]
I have looked through the SAR data and could not find anything about ethers with the end phenyl being replaced with a 5 member ring

**Comment by MedChemProf** [comment]
@mattodd This may have been discussed previously, so my apologies up front if that was the case. I was reviewing a few papers that I have been accumulating and focused in on a J.Med.Chem (2015) 58, pp. 8713-8722 paper on some antimalarial imidazopyridazines / pyrazolopyridines. Two of the more potent structures are shown below:
![1](https://cloud.githubusercontent.com/assets/14179120/15021902/3d625f7e-11f7-11e6-91d3-ebe2d6ca9da5.jpg)
It started to make me think that the meta-sulfone may be contributing to activity in a similar manner to the analogs that have branched alcohols and amines (like MMV670947). It was also already demonstrated that the positional isomer on the triazolopyrazine ring system also can be active (MMV670945).
![2](https://cloud.githubusercontent.com/assets/14179120/15022214/96acee68-11f8-11e6-85ff-e1ecba5ebb87.jpg)
Since one of the biggest hurdles at the moment is the trend toward higher LogP's, I was wondering if we missed the opportunity to include the sulfone and sulfoxide analogs described in the paper. Would it make sense at this point to target a few analogs like the ones shown below? (I have only shown the sulfone-sulfoxide analogs, but the sulfone-sulfone could also be made. There was discussion on this in the previously mentioned paper.)
![3](https://cloud.githubusercontent.com/assets/14179120/15022310/1a010aa6-11f9-11e6-9392-f7e4521ed3a0.jpg)

**Comment by MFernflower** [comment]
Edwin may be producing a few sulfonamides for testing (I chatted with him).
Are cyclopropyl rings really that stable? If so I could try and make up a
prototype molecule by the end of the day

**Comment by MFernflower** [comment]
#382

Edwin may be producing a few sulfonamides for testing (I chatted with him). Are cyclopropyl rings really that stable? If so I could try and make up a prototype molecule by the end of the day

**Comment by MedChemProf** [comment]
These initial analogs do not use the sulfonamide linker, they are sulfones or sulfoxides remote from the linker position.

**Comment by MFernflower** [comment]
Do you have the SMILES strings for the bottom set of molecules? I would like to do some energy minmazation and use them as a base for my sulfonamide idea

**Comment by MFernflower** [comment]
@MedChemProf I came up with two ideas that integrate sulfonamide groups:
(Links are to chemicalize computation pages) 
http://bit.ly/1SP6yuh
http://bit.ly/1OevEka

**Comment by MedChemProf** [comment]
O=S(C)C(C=C1)=CC=C1C(N23)=NN=C3C=NC=C2OCCC4=CC(S(C5CC5)(=O)=O)=CC=C4
O=S(C1=CC=CC(COC2=CN=CC3=NN=C(C4=CC=C(S(C)=O)C=C4)N23)=C1)(C5CC5)=O
O=S(C)C(C=C1)=CC=C1C(N23)=NN=C3C=NC=C2OCCC4=C(S(C5CC5)(=O)=O)C=CC=C4
CS(C(C=C1)=CC=C1C(N23)=NN=C3C=NC=C2OCC4=C(S(C5CC5)(=O)=O)C=CC=C4)=O

**Comment by MFernflower** [comment]
Thanks! Did you see the two ideas I came up above?

**Comment by MFernflower** [comment]
@MedChemProf Thanks! What did you think of my two ideas that integrate sulfonamide groups into them?

**Comment by MFernflower** [comment]
@medchemprof Thanks for the SMILES strings! Here are two ideas I came up with:

N1(CCCC1)S(=O)(=O)C1=C(C=CC=C1)CCOC1=CN=CC=2N1C(=NN2)C2=CC=C(C#N)C=C2  LogP: 1.87

C1(CC1)S(=O)(=O)C1=C(C=CC=C1)CN(S(=O)(=O)C1=CN=CC=2N1C(=NN2)C2=CC=C(C=C2)OC(F)F)C LogP: 1.85

**Comment by mattodd** [comment]
Interesting idea @MedChemProf - synthetically that might be quite straightforward, and the impact in cLogP is dramatic. We should look at how easy it might be to make the required coupling fragments - the aldehyde for the northeast and the alcohol for the northwest. Could I ask that if we pursue this more that we separate this out to a separate Issue - we're supposed to be talking about cubane here...

**Comment by mattodd** [comment]
Good news - Craig Williams has agreed to try to send us a sample of 2-cubylethanol which we can couple with the chloro precursor to make a final cubane analog. Craig says that the cubane aldehyde (for the northeast) is difficult to handle, but that the “para”-iodo carboxylic acid is available and we could reduce that to the aldehyde, which ought to be easier to handle. He’s offering to ship that acid too. These are valuable new inputs that should allow us to evaluate the effectiveness of cubanes in these compounds as phenyl isosteres. Craig is happy to share the experimental details of relevant transformations in the spirit of the open project.

**Comment by MFernflower** [comment]
That is fantastic!!!!

**Comment by mattodd** [comment]
Cubane samples have arrived in Sydney from Craig Williams. Synthesis should begin shortly - link will appear here when it does.

**Comment by MFernflower** [comment]
@mattodd Just checked @edwintse 's ELN and he has appeared to have successfully produced the left hand cubane - No idea when the right hand cubane and the sulfonamides are to be produced?

How long does it take to get test results from syngene? Im really looking forward to them and the upcoming webinar

**Comment by edwintse** [comment]
Synthesis using the cubane samples are in progress. See Issue #395.

**Comment by edwintse** [comment]
With the interesting potency results received from the cubane bioisosteres ([here](http://malaria.ourexperiment.org/uri/b06)) it was seen that we were lacking a comparison for the RHS replacement (OSM-S-375) and whether or not it was the size of the iodine that was the issue. The para iodo phenyl analogue has just been synthesised and will be sent for testing in the next batch.

**Comment by mattodd** [comment]
Could you just insert the string in the above, @edwintse , and the link to the latest ELN entry? Ta.

**Comment by edwintse** [comment]
Cubane analogues were made last year. Results are [here](https://github.com/OpenSourceMalaria/Series4/wiki/Biological-Data-currently-not-incorporated-into-the-main-Wiki-sections) among other hydrocarbon cage bioisosteres. Closing this issue.
