### ISSUE TITLE
The Tianyi -- proposed synthesis Haverford College

### ISSUE THREAD

**Issue by rbroadrup-HC** [OpenSourceMalaria/OSM_To_Do_List#410]
Proposed synthetic routes have been developed in collaboration with students as part of an organic chemistry class I teach at Haverford College. The molecules are seen as being desirable targets as per #390. This Issue has been created for community feedback on the routes, which can then be attempted in the lab by us or others.

![the tianyi](https://cloud.githubusercontent.com/assets/19805430/15872010/4e593c56-2cc5-11e6-832d-feae47b4637f.png)

CC1=C(C2=CC=C(OC(F)F)C=C2)N3C(C=NC=C3OC[C@@]([H])(C4=CC=CC=C4)O)=N1
InChI=1S/C22H19F2N3O3/c1-14-21(16-7-9-17(10-8-16)30-22(23)24)27-19(26-14)11-25-12-20(27)29-13-18(28)15-5-3-2-4-6-15/h2-12,18,22,28H,13H2,1H3/t18-/m0/s1
VGNPLLBRBOUQAA-SFHVURJKSA-N

**Comment by MFernflower** [comment]
@rbroadrup-HC  Would you consider producing my bicyclic terpene idea? 
![img_20160601_234113](https://cloud.githubusercontent.com/assets/3164942/15872767/11841554-2cc9-11e6-8701-634a83071cdc.jpg)

**Comment by rbroadrup-HC** [comment]
Love to.  Meeting with a beekeeper now.  Will be in touch.  R

**Comment by alintheopen** [comment]
I'm v. interested in the difluoromethylation step. I do think it is better for the students to start with 4-(Difluoromethoxy)benzaldehyde for synthetic ease and precedent in the project, I like that this reagent has been considered. I looked up the [paper](http://www.sciencedirect.com/science/article/pii/S0040402009006553) and SDS and it does indeed seem, as stated, to be a 'benign difluorocarbene precursor'. The paper details it's use in functionalisation of phenols and thiophenols but doesn't mention (unless I missed it in a quick scan) the use of aliphatic alcohols. We could really use a method to introduce this group. The 'difluorocarbene' reagent I have tried gave no joy, although [I do have a friskier relative waiting in the cupboard](http://malaria.ourexperiment.org/the_osm_blog/8470/post.html), which we could revisit once the health and safety forms have been resumed. A benign alternative would be great since we have already established that it isn't possible to use Freon gas in Australia.

**Comment by MFernflower** [comment]
@alintheopen Just got an update from http://www.enamine.net/ on my twitter page - They are stocking some interesting things:
![ckm365hvaaelpoi](https://cloud.githubusercontent.com/assets/3164942/15982587/4fc9256a-2f59-11e6-9341-351ca013ca01.jpg)

**Comment by MFernflower** [comment]
@alintheopen Sigma stocks the methyl ester for dirt cheap if that's of any help to you

http://www.sigmaaldrich.com/catalog/product/aldrich/390755?lang=en&region=US

**Comment by MFernflower** [comment]
@rbroadrup-HC Why don't you produce the 5-chloro-3-[4-(difluoromethoxy)phenyl]-2-methylimidazo[1,2-a]pyrazine fragment first and then couple it to the same protected alcohol used to make MMV688895? - a simple protection in acid followed by purification/recrystallization should give the product in (hopefully) good yields

**Comment by mattodd** [comment]
@rbroadrup-HC am I right in thinking this is not being pursued experimentally in the Superlab? If so we should close this Issue for now but retain this compound (and this Issue) on a list of potential targets on the Series wiki.

**Comment by alintheopen** [comment]
I received this email from Lincoln Satterthwaite (thanks Lincoln!) on Sept 21st, posting here so that we can all offer some advice:
"Alice, 
My lab partner and I have been working on the synthesis of the triazolopyriazine core via the route outline by [Tom McDonald](http://malaria.ourexperiment.org/triazolopyrazine_se/11034/Repeat_synthesis_of_5chloro124triazolo43apyrazine_TM_3714.html), but we're not having much luck with the first step of the synthesis. We get what appears to be the crude product (based on the images from Haochuan Mao here, but we can't see it in an NMR after running a column using 30% EtOAC in hexanes.
My question for you is this: were there any special conditions that you used for the column/reaction when you did it? Light sensitivity, higher heat, etc. Any help would be greatly appreciated.
Best,
Lincoln"

Hi Lincoln, I wonder if the product has stuck to the column? Did you flush the silica with 100% EtOAc at the end? Haochuan used a Biotage Isolera to purify his compound (an automated columning machine) and also managed to recrystalise from the crude - from memory using EtOAc. Haochuan also modified the synthesis to add the reagents at different stages which prevented the formation of a heterogeneous mixture: See the Log part of [HM 1-5](http://malaria.ourexperiment.org/triazolopyrazine_se/14415/Synthesis_of_5chloro124triazolo43apyrazine_HM_15.html)
Hope this helps! Will email Haochuan too to ask for any advice! Cheers Alice

**Comment by alintheopen** [comment]
Email from Haochuan who can't access GH now he's back home in Nanjing:

"Hi Lincoln,
I'm so excited that you read my lab notebook.
I didn't use any special condition for that reaction or column, and the refluxing temperature was about 110 degree Celsius. But the I used 75% of EtOAc in hexane as the fluent phase when conducting the manual column,because the desired product was quite polar and I even tried 100% of EtOAc directly using Isolara and the result was good. I hope this can be of help.

Plus, as was mentioned by Alice, adding catalyst later will help rid the reaction off some annoying sticky solid.

Good luck!
Haochuan"

**Comment by mattodd** [comment]
Hey @alintheopen not sure the above two comments are in the right place - this issue is on the Tianyi compound. If so, can you delete and add to the right Issue, and then delete this (my) comment?

**Comment by mattodd** [comment]
Closing this Issue for now. The need for the compound has been added to the "[desirable compounds](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised)" section on the wiki, and a synthetic branch has been installed on [the relevant page](http://openwetware.org/wiki/OpenSourceMalaria:Synthesis_Branches). This compound is **_still needed_**, and can be found here again through a search on "Tianyi"
