### ISSUE TITLE
Quick Request re Haverford Superlabs

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#426]
Sensational that the Haverford students are starting in the lab @rbroadrup-HC . Also great that the lab books have been started - all very exciting. A quick logistical request. Looking at the lab notebooks now listed [here](http://malaria.ourexperiment.org/?allblogs), I wonder if the new lab books you've created could all have their names prefaced with e.g. Haverford, so that they group together in the notebook list a little? We've not had this problem before, but I think with the proliferation of notebooks it might make sense to add a little order. If not trivial, ignore. Either way I'll close this issue soon - it's a minor request.

**Comment by rbroadrup-HC** [comment]
Hi Mat,

Very exciting!  I'd be happy to ask them to make the change.  Do you know
if that's something then can change after the issue has been created?  Have
a great weekend, and I'll stay in touch as the quarter and semester
progress!

Best,
Rob

On Sep 1, 2016 11:21 PM, "Mat Todd" <notifications@github.com> wrote:

Sensational that the Haverford students are starting in the lab
@rbroadrup-HC <https://github.com/rbroadrup-HC> . Also great that the lab
books have been started - all very exciting. A quick logistical request.
Looking at the lab notebooks now listed here
<http://malaria.ourexperiment.org/?allblogs>, I wonder if the new lab books
you've created could all have their names prefaced with e.g. Haverford, so
that they group together in the notebook list a little? We've not had this
problem before, but I think with the proliferation of notebooks it might
make sense to add a little order. If not trivial, ignore. Either way I'll
close this issue soon - it's a minor request.

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/OpenSourceMalaria/OSM_To_Do_List/issues/426>, or mute
the thread

**Comment by mattodd** [comment]
Yes - looks like it's already happening, [here](http://malaria.ourexperiment.org/?allblogs)! If the others could do the same, that'd be great, thanks.
