### ISSUE TITLE
How Shall we Write the Series 4 Paper, Share Files?

### ISSUE THREAD

**Issue by mattodd** [OpenSourceMalaria/OSM_To_Do_List#443]
Further to my comment in #358 just now:

A perpetual issue has been how to operate a shared file store for OSM, and which to use? A non-trivial problem. I suspect Dropbox would work, as, perhaps, would Slack. I had hoped we might be able to use Github for this, given that we're all already here. The [wiki](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series) images are helpful for summarising progress to date. The original intention, 5 years ago or so, was that the writing of the wiki would be essentially the same activity as writing the paper, to avoid duplication. Results would be folded in as they came in. I don't think there's a platform for this, and the problem with the wiki is that it's _another_ sign in.

However, perhaps people could look at [the repository I started for the first Series 4 paper](https://github.com/OpenSourceMalaria/OSMSeries4Paper1) which is something we need to re-activate in the coming months. There is a Word document there that can be downloaded, edited and re-uploaded by, I think, anyone in the associated team. One can post chemdraw files there, and, I think, lots of other filetypes. Perhaps it's time for us to step outside of Github as merely a To-Do list and start using its filesharing capabilities more properly for paper writing, _properly versioned_. I wonder, then, if there's a way we can maintain a Word file as the current status of the project document, with this To Do list acting as a place to discuss things related to the paper specifically. Alternatively the paper is constructed in these windows with markdown, and then converted to a Word document later. I suspect that is a better option, though slightly beyond my technical abilities. Writing the paper while maintaining project status involves a complex web of activities that needs to make sense to everyone, so I'd be grateful for suggestions as how best to do this (in a way that permits open filesharing).

My suspicion is that if we can all master submitting pull requests and accepting them, then we may have a much more powerful paper writing platform here than we appreciate.

**Comment by Daniel-Mietchen** [comment]
Some quick thoughts while cheering from the sidelines:
- I'm not sure why you'd want to convert the final thing to Word, but Google Docs would seem a reasonable basis for that, and they can be used without additional logins.
- GitHub works great for collaborative writing in txt/ tex/ md and similar.
- Of these three, TeX seems to be the most advanced for handling chemistry but can't be rendered on GitHub.
- Have you had a look at [Overleaf](https://www.overleaf.com/)? If one author has a login, things can be set up so that others can join in without an additional login.

**Comment by MedChemProf** [comment]
@mattodd What is your expected timeline on the completion of the Series 4 paper? I know we have struggled to get the reversed amides completed and tested, but I think we are close to solving some of our synthetic issues. We were hoping to contribute that SAR point at least.

**Comment by mattodd** [comment]
ASAP, but we have a colossal amount of data to write up, and we require further biological data on the frontrunners. I'll be coy and say 2017.

**Comment by MedChemProf** [comment]
@mattodd Thanks! We will try and stay razor focused. The issue is that we can synthesize the azido-substituted triazolopyrazine pretty well, but the reduction of the azide has been problematic. The Staudinger (Ph3P/THF/H2O) produces the stable iminophosphorane which we have not been able to hydrolyze, hydrogenation gives the product amine, but in low yields and multiple by-products, and borohydride reduction performs similarly to hydrogenation. I would like to say that your 2017 estimate gives us breathing room, but after the beating we have been taking I can't say for sure. ;)

**Comment by MFernflower** [comment]
@mattodd were anymore componds shipped off for testing?

**Comment by mattodd** [comment]
A little off-topic @MFernflower so I'll delete this shortly. Answer - @edwintse is working on the final compound as per #435 . An alert will be posted as soon as they're in the air.

**Comment by mattodd** [comment]
Closing since Series 4 paper 1 can now be started, as per #532 and Chase's reversed amides were synthesised as per #487
