### ISSUE TITLE
Back Ground Questions about "The 8"

### ISSUE THREAD

**Issue by rainafitz** [OpenSourceMalaria/OSM_To_Do_List#444]
1. Most of the other aromatic rings on the pyrazine side chain other structures on OpenWetware, have one or two fluorine atoms on the aromatic ring. Similarly, the representative compound for OSM has one meta chlorine on the ring. The 8, instead, simply has an aromatic ring with an alcohol group sharing the carbon. Why were the halogens eliminated from this ring, and why was the alcohol added?
2. A post on the GitHub To Do list (#402) had a comment mentioning that while substitutions at the 8 position typically decreases potency, the methylation there will be useful in the aldehyde oxidase activity, and potentially for a pull-down. We have researched the aldehyde oxidase assay and understand it is a measure of metabolism by the aldehyde oxidase enzyme specifically on carbons adjacent to aromatic nitrogens. Why is a methyl group preferable to the other 8-position substitutions? What about the metabolism of the compound would the AO elucidate?
   ## 
3. A compound being synthesized by another group, “The 6” differs from ours only in the methylation location. Was the ultimate goal for this target an AO assay as well?

**Comment by mattodd** [comment]
Hi Raina,

The 8 (structure in #402) uses a regular phenyl just for simplicity. We know that halogen substitution on the ring can help potency, but the simpler aromatic ring is easier to source inexpensively then the halogenated varieties. When we're exploring new chemistry it's a good idea to simplify where you can. It'd be easy to adapt to other rings in the northwest later. The -OH in the benzylic position is just to help with solubility - we have a rule that we're targeting only compounds with cLogP values less than 3.5. Again, if that's a problem, then we can initially not have the -OH for working out the chemistry, then add it in later.

Yes, the AO appears to target Ar rings next to N. So putting a methyl in this position should slow this down. We can measure AO at Pfizer, courtesy of Scott Obach. So this compound and the "6" can be compared to those compounds lacking those groups to see if there is an impact on the rate of metabolism. We can at the same time check for clearance rates in simple microsomal stability assays. In some senses it doesn't matter too much if these compounds are potent or not, since we're addressing a different question here. If we can make the methyl-substituted compounds we can put other groups there too, in the future. If the 8 or the 6 _are_ potent, then we might be able to put biotin there for pull-down experiments. It's worth checking the potency of some compounds for which we already have some data, since remember that we inherited a significant amount of data for this series.

**Comment by mattodd** [comment]
Link installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki. Closing.
