### ISSUE TITLE
NMR splittings in the alkyl

### ISSUE THREAD

**Issue by OHaraJansonSchankler** [OpenSourceMalaria/OSM_To_Do_List#454]
We have been working on synthesis of the alkyl #431 and have noticed some strange splittings in the NMR of our step 3 product. The doublets at 7.33 and 7.77 ppm should correspond to protons 12 and 16 and 13 and 15 respectively. We expect them to be doublets integrating for 2H (and we observe them to be in precursors with similar functionality), but in our step 3 product, we see what appear to be quartets superimposed on the doublets: (1H NMR in dmso shown below)

![rxn3r2_proton_dmso](https://cloud.githubusercontent.com/assets/19557496/19714648/e10f880e-9b1d-11e6-9cc6-c0d8b269a1ed.png)
![rxn3r2_proton_dmso_zoom](https://cloud.githubusercontent.com/assets/19557496/19714649/e10f8fe8-9b1d-11e6-9795-84a8ce40dda2.png)

These quartets exactly overlap the doublets both in dmso and in cdcl3 and are about the same relative size across two syntheses of this compound. We think that this suggests that the peaks are not impurities but rather additional splittings of these hydrogens, but we are not sure what could be causing these splittings or why these quartets seem to increase the integrations.

**Comment by MedChemProf** [comment]
@OHaraJansonSchankler Your spectrum is actually very good. The peaks you are observing are doublets, but there are also what is known as 'Second Order Effects' showing up. This is common between coupled peaks that are separated by large chemical shifts relative to their coupling constants. If you look at the 1H NMR of similar compounds in the ELN, you will see they show this more complex pattern also.

**Comment by mattodd** [comment]
Yes, excellent spectrum. But as Chase suggests, this compound has been made a few times before @alintheopen @edwintse so you can compare. In the absence of a good chemical searching functionality in the ELN, this is why we use SMILES and InChI codes in webpages when we can so that we can find relevant compounds using e.g. Google. Here, for example, you're talking about ClC1=CN=CC2=NN=C(C3=CC=C(OC(F)F)C=C3)N21 or InChI=1S/C12H7ClF2N4O/c13-9-5-16-6-10-17-18-11(19(9)10)7-1-3-8(4-2-7)20-12(14)15/h1-6,12H

**Comment by PatrickThomson** [comment]
The integrals for the (impressively split) H on the OCHF2 group are consistent with the para-benzene ring but it looks like the ones for the heteroaromatics are a little low as a result. Was this the same in previous incarnations of this compound?

**Comment by aschankler** [comment]
@PatrickThomson We didn't notice a large discrepancy in the integrations until we started running these higher resolution spectra. I re-integrated the spectra of our last two products in cdcl3 and normalized to the peak at 7.89 ppm, and the effect was much less pronounced:

![rxn3r2_proton_cdcl3](https://cloud.githubusercontent.com/assets/19557496/19744553/faf57d4a-9b9b-11e6-8199-0cd1f7a87c6f.png)
![rxn3r3_proton_cdcl3](https://cloud.githubusercontent.com/assets/19557496/19744554/fafca804-9b9b-11e6-88f7-de7f456ef9ce.png)

But when I integrated spectra of the same two samples run in dmso, the effect was still very noticeable.

![rxn3r2_proton_dmso](https://cloud.githubusercontent.com/assets/19557496/19744790/00720fd0-9b9d-11e6-8be7-572efbf79301.png)
![rxn3r3_proton_dmso](https://cloud.githubusercontent.com/assets/19557496/19744745/d3e98eca-9b9c-11e6-9ecf-e2e081961b1d.png)

Any idea what might be causing the low integrations heteroaromatic Hs.

**Comment by MedChemProf** [comment]
@aschankler I think the simplest explanation is that the pulse sequence you are using for running the 1H spectra is designed to be general use and it is not optimized for your particular compound. The delay between pulses may not be sufficiently long enough to allow all protons to relax back to their ground state before the next pulse. This is easily tested if you have the same NMR sample. Speak to the instrument manager and they will be able to quickly show you how to make some changes to the pulse sequence to allow you to get more accurate integration measurements.

**Comment by mattodd** [comment]
Agreed @MedChemProf - we have had to tweak the pulse sequence if we have such protons in compounds and need to get the integrals perfect, or if we're using NMR spectroscopy for kinetics. Minor discrepancies (20%) in such integrals are usually acceptable for publication. The crucial thing **for publication** is to demonstrate purity (i.e. one compound, no residual solvent peaks) before biological testing of compounds.

**Comment by aschankler** [comment]
@MedChemProf @mattodd Unfortunately we don't have the samples ready to go and are actually getting ready to hand our project off to another group. Would you recommend that the next group spend a little time redoing the NMRs to try and get better integrations for the precursors?

**Comment by aamilder** [comment]
Just to tack on here, @aemorrison and I are working with a similar compound and have seen similar patterns in our step 3 which is identical to yours. We used CDCl3 rather than DMSO but our spectra look pretty much the same. The peak at 7.27 is "over integrating" for us as well, but as @mattodd points out that may not be that big of a deal. One thing, however, is that the proton in the OCHF2 group results in an massively split triplet that you have integrated as three separate peaks. If you combine those peaks the integration should reach about 1, which will help clear up at least part of this. I think this is what @PatrickThomson was getting at. Otherwise I guess the fact that we got similar looking spectra may indicate something about the NMR machine that we are all using.

**Comment by aschankler** [comment]
@aamilder I agree I noticed similar artifacts in #451 so it's probably something to do with the defaults on our instrument. In terms of the integrations, we integrated the triplet separately so that we could separate it from the superimposed doublet. I think the triplet adds up fine, it was the protons on the core that were under-integrating.

**Comment by mattodd** [comment]
Hi @aschankler - yes, if we're to publish this work we need high quality samples and high quality NMR spectra of those samples. Like I said, the integrals can be slightly out for protons like this, but the spectra cannot contain impurity peaks, including solvent peaks. Getting this sorted out now will ensure that your compounds can be incorporated into an OSM paper without the need for resynthesis later.
Could you please install a link to this discussion in one relevant page of your ELN so that we don't orphan the page. When you've done that you can close this Issue I think @aschankler  , unless anyone has anything more to add.

**Comment by aschankler** [comment]
Reference to this issue added [here](http://malaria.ourexperiment.org/reduced_alkyl/14793#690).
