### ISSUE TITLE
Background Questions about "The Alkyl's"

### ISSUE THREAD

**Issue by sdilones** [OpenSourceMalaria/OSM_To_Do_List#455]
Me and @anna-schrecengost are currently looking into the history of the alkyl (specifically with an internal alkyne) and just had a couple of clarifying questions:

![alkyne](https://cloud.githubusercontent.com/assets/21691707/19755783/01d412c6-9be6-11e6-8d04-e2397a38ee49.jpg)

1) What exactly makes the side chain a potential metabolic hotspot?
2) Why does adding more than three atoms cause it to lose potency?
3) Why exactly did replacing the the triazole aryl substituent with a cyclo(hetero)aliphatic group lower the potency?
4) The internal alkyne,can only occur because of the benzylic oxidation, and without any substituents on the benzene, the alkyne can't occur, right?

**Comment by mattodd** [comment]
Hi - you saw #457 , right? The compound you show is not an "alkyl" - it contains an alkyne functional group. I think we need to be careful with terms to avoid confusion. Brief answers to questions:
1) Normally benzylic positions can be hotspots - easier to oxidise. But it depends. I don't know about alkynes as hotspots, but really the alkyne is intended as a useful synthetic precursor to other analogs downstream.
2) No idea. It'd be nice to know. We don't have the biological target, see #421 
3) Don't understand - can you provide MMV or OSM compound numbers or links to relevant structures so that we can see which structures you mean?
4) Ahm, I don't understand your sentence, sorry.

**Comment by mattodd** [comment]
As per #423 closing this now. Added this issue to [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki.
