### ISSUE TITLE
Alternate Route to the methylated dichloropyrazine

### ISSUE THREAD

**Issue by rainafitz** [OpenSourceMalaria/OSM_To_Do_List#456]
In our synthesis of the 8 Caroline McKeon and I were having no success in methylating the 2-6-dichloropyrazine. Our solution was to chlorinate a 2-methylpyrazine instead by oxidizing the starting material to a 2-methylpyrazine 1N,4N-dioxide and then reacting that with POCl3. 
![route4](https://cloud.githubusercontent.com/assets/21690010/19785417/47dbf582-9c67-11e6-8702-859774c25b9f.png)

Our first step (synthesis of the 2-methylpyrazine 1N,4N-dioxide) was successful but our chlorination step seems a little off. The H NMR does not show the peaks associated with our expected product and the GCMS shows a molecular weight of 127 g/mol which is about what the weight would be if we had only added one chlorine to the pyrazine. We are letting another group take over this synthesis but if anyone has any insights into why our reaction resulted in this spectra it would be greatly appreciated. We are mostly curious as to why the H NMR shows a peak at 7.25 ppm and two small peaks between 9 and 8, and weather or not the GCMS is indicating that we only chlorinated one carbon.

With that being said we are pretty hopeful that this alternate route will be easier than doing the methylation and we believe the next group will be looking into other means of chlorinating the 2-methylpyrazine 1N,4N-dioxide.

Here is a link to our lab notebook: http://malaria.ourexperiment.org/superlabthe8
Phosphorylation GCMS
[phosphorylation_GCMS_annotated2.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/557034/phosphorylation_GCMS_annotated2.pdf)
H NMR
[S2_Proton.pdf](https://github.com/OpenSourceMalaria/OSM_To_Do_List/files/557035/S2_Proton.pdf)

**Comment by mattodd** [comment]
Yes, I think it's mono-chloro. The 7.25 is residual CHCl3, and the other two peaks must be the H's arising from the mono-chloro ring. If you agree, then we can close this issue.

However, could you please just deal with some housekeeping here? 

1) Add hyperlinks to your text above that links directly to the reactions you're talking about, e.g. a successful example of the first step. I'm assuming that the spectra you've added to the above post are already on the ELN? If not could you please make sure that they are up there?
2) Add SMILES, InChI and InChIKey strings for the molecules you mention to the bottom of your original post above.
3) Install links to previous issues on "The 8" by mentioning them like this: #429 This enables us to keep track of all issues related to the synthesis of a particular molecule, because back-links from those Issues to this one are automatically created. The group coming after you will thank you forever.

**Comment by mattodd** [comment]
Closing since I think this attempt at this target is parked. Potentially being taken on further in #461 . Links installed in [DCNYS](http://openwetware.org/wiki/OpenSourceMalaria:Triazolopyrazine_%28TP%29_Series#Desirable_Compounds_Not_Yet_Synthesised) section of wiki.
FC(F)OC(C=C1)=CC=C1C2=NN=C3C(C)=NC=C(OCC(O)C4=CC=CC=C4)N32
InChI=1S/C21H18F2N4O3/c1-13-19-25-26-20(15-7-9-16(10-8-15)30-21(22)23)27(19)18(11-24-13)29-12-17(28)14-5-3-2-4-6-14/h2-11,17,21,28H,12H2,1H3
ASWYMQOLUDKKDJ-UHFFFAOYSA-N
