### ISSUE TITLE
Takeover of the Burns Synthesis Haverford College Superlab Q2

### ISSUE THREAD

**Issue by vribeiro3** [OpenSourceMalaria/OSM_To_Do_List#459]
@brettpogostin and I will be taking over the "Burns" synthesis of Quarter 2 Superlab at Haverford College previously started by @claudianguyen95 and @evonkrusenstiern. Our new proposed synthesis will be based off theirs (#422) as well as the consultation on the chem (#438, #450)

The previous group got to step 4 of the synthesis. However, their product was not exactly what was wanted (it also had a low yield). @brettpogostin and I have proposed an alternative synthesis that would address this issue and change a few others steps to accelerate how far along we can get in the synthesis.
![osce](https://cloud.githubusercontent.com/assets/23084374/20110792/bdf516d6-a5b3-11e6-9822-46fceb27d31f.png)

 We will be recording our work in [this lab notebook](http://malaria.ourexperiment.org/hc_superlab_).

**Comment by mattodd** [comment]
Sounds great @bpogostin and @vribeiro3 , welcome aboard guys!

Please do post everything in real time to your ELN. Don't worry about whether or not people will read it - the data all need to go there. To ensure it's machine readable, please try to add SMILES, InChI and InChIKeys to the posts - in fact would you mind adding these strings to your initial post above?

With your reaction numbering, are you able to use something akin to [this system](http://openwetware.org/wiki/Todd:Guidelines#Reaction_Numbering), so we are always clear which compound/reaction you're talking about? [your initials]-[reaction number (i.e. S/M to product regardless of reagents)]-[attempt-number] etc?

With Github it's really easy and useful to install backlinks to related issues, like this: 
Original Burns discussions (#358, #388), original proposed synthesis (#404), starting the synthesis (#422), consultations on the chem (#438, #450). (I wonder if we might be able to close #422, what do you think?). This makes collecting everything together for publication etc so much easier.

I'm adding the tags for "Series 4" and "Being Synthesised Now". 

Remember that these Issues are meant to be closed. Have a think about what needs to be established (by you) for this issue to be closed. Maybe when you next post a summary of a result you have, or a reaction that has worked, you could close this issue since you're no longer seeking input on it?

Last thing. For us looking on (and cheering you on) do you think you'd be able to post a quick picture below that summarises where the previous group got up to, and hence where your immediate focus is? That can help bring everyone up to speed.

**Comment by mattodd** [comment]
btw Github tells me @bpogostin is not a member yet, so can't add to the "core contributing" group that gives extra privileges.

**Comment by MFernflower** [comment]
The ester is buyable from alfa for about 90 USD a gram. This will save you time so that you can work on improving the yield of step 3


https://www.alfa.com/en/catalog/H66682/


@vribeiro3

**Comment by BrettPogostin** [comment]
We have spent the last few weeks working on on the first fluorination step. The past group reported a 10% yield, but looking back at their results, they may have not successfully synthesized the product at all. We too were unsuccessful, and our attempts can be found in our lab notebook. For future attempts, I would suggest finding an alternate synthesis route. This reaction is very tricky and hard to monitor.


For reference, this is the reaction we attempted:
![the burns new step 2](https://cloud.githubusercontent.com/assets/23084323/21062168/9213537a-be1d-11e6-8c93-4397a6c5c2b8.jpg)

**Comment by mattodd** [comment]
Hi @BrettPogostin - does this mean you're finished with this attempt and we can close this Issue? If so, please use the "close" button below, and please do make sure all the data you generated are on the lab notebook before finishing up.

**Comment by BrettPogostin** [comment]
I don't see one. Sorry for being so bad at using github!

**Comment by vribeiro3** [comment]
The semester has come to an end, so we are closing this issue for now.
