### ISSUE TITLE
Newcomer: where to start?

### ISSUE THREAD

**Issue by mcoster** [OpenSourceMalaria/OSM_To_Do_List#505]
I've been aware of OSM for some time, but haven't followed it closely, or contributed, until now. I have a final year undergrad project student (2 days/week * 12 weeks) who is interested in a synthetic project contributing to OSM. Thinking longer term, I am interested in getting more undergrad project students involved in future if we are able to make useful contributions.

Any suggestions for where a complete newcomer can make useful synthetic contributions?

**Comment by mattodd** [comment]
Woo-hoo! Hi Mark. What you describe sounds very good. I just met with @alintheopen to talk about this and she'll post up something next - there's a really nice discrete project based on what @jaspert95 was doing in #493 . 
(More generally, in an ideal world, it should be clear what is most-needed so that you don't need to ask. These Github issues are meant to be clearly delineating project needs, but they are also supposed to be linked to an up-to-date summary of where we are all up to in each series, and linked to papers that are being written up. We've been ruminating on this a lot and I think that, because we've grown a fair bit, we need a fairly serious migration of project components over to Github, and away from our current wiki/paper writing solutions which are a bit fragmented. More on that ASAP. In the meantime, we'll do this old school and highlight a specific project for your consideration.)

**Comment by mcoster** [comment]
Thanks @mattodd - good pointer. I did eventually stumble on the [synthesis branches](http://openwetware.org/wiki/OpenSourceMalaria:Synthesis_Branches) page and noted OSM-CH and OSM-BrCl as potential branches we could contribute to.

**Comment by MFernflower** [comment]
What about making some of the compounds on the DC-NYS section of the wiki?

**Comment by mattodd** [comment]
Sure, @MFernflower, those are all still needed, and I think that the wiki is still reasonably up to date. I'll let @alintheopen mention a couple of things related to core halogenation, towards the Norcross compounds, as other possibilities.

**Comment by mcoster** [comment]
Thanks for the suggestions. Have reformulated this question as a proposal now - #508.
