### ISSUE TITLE
Future of OSM

### ISSUE THREAD

**Issue by drc007** [OpenSourceMalaria/OSM_To_Do_List#576]
I've been thinking about this for sometime but the recent [review](https://github.com/OpenSourceMalaria/OSM_To_Do_List/blob/master/General%20Papers/2018%20Malaria%20Pipeline/MMV_Review_V6.pdf) posted by Matt and the a more detailed examination of the [MMV website](https://www.mmv.org/research-development/mmv-supported-projects) has led me to wonder if this is a good time to reassess.

The impact of MMV funding is clear to see, we now have 7 approved drugs/formulations with another 7 clinical trials ongoing, with novel modes of action identified. The prospects for successful malaria treatment have never looked better. On the other hand we have many other neglected diseases for which there are no safe/effective treatments. Whilst there will always be concerns about resistance malaria is not a neglected disease.

Should the OSM team be moving their considerable efforts and talents to focus on other diseases?

**Comment by mattodd** [comment]
Thanks for posting @drc007. Great question. I'll be interested to hear peoples' thoughts. Some quick points from me.

1) Though the malaria pipeline is looking much better than it was, the attrition rate is still high. There are several PfATP4-targeting drug candidates for example, but there's no guarantee anything will make it. MMV themselves deal with this issue all the time. There are remarkably few novel MoA therapies reaching patients. The answer here is that, on balance, though the pipeline is healthy, *one cannot be complacent*.

2) Malaria is a fascinating area for open science since the economics are more "interesting" than for some NTDs. There is the possibility of a profit. That makes it a good area for open since the economics is more thorny.

3) Series 4 is advanced, with in vivo actives. Series 3 is a beautiful hit. I, and I think others, want those projects to progress. There are many series one could imagine hosting in OSM as S5, S6.. where people can run their own activities. OSM will be a powerful repository.

4) I'm actively seeking funds for all of this, by the way, and I am encouraging everyone I talk to to do the same.

5) There are already projects in other areas, e.g. mycetoma, and a dormant TB community. I'm trying to raise funds for both from UCL, and would be interested in working with anyone to do the same. Recent conversations with people I've had here have been around possible future consortia in leish and antibacterials. What about rare diseases? Dementia? I would love to clone our approach and work in these other areas. We would then need to talk about projects, leaders and resources. My job here is to raise money to drive things, but of course these are all open source communities, meaning people are able to act independently. The reason I mention resources is purely that I want to make sure we (OSM contributors and potential contributors) do not spread thinner, but rather that we scale well if we apply ourselves to fresh areas.

Please chip in, anyone.

**Comment by MFernflower** [comment]
@drc007 I have been doing a bit of work regarding the mycetoma project if your interested

**Comment by holeung** [comment]
I agree with @mattodd. It's probably because I've only been involved for two years, but I feel like we're just getting started. As everyone knows, the chances of any particular lead making it to patients are slim so we need many shots on goal. And if we can expand our scope to study mechanisms of action and resistance and target identification, we can make major scientific contributions.

I am trying to follow in @mattodd's footsteps and help with bringing in money and pushing publications. I see bringing in money as the most straightforward way to make faster progress. And at least for academics, to bring in money, we need to publish.

I am interested in doing some kind of open source cancer project someday.

**Comment by drc007** [comment]
This report is timely, [Access to Medicines](https://accesstomedicinefoundation.org/news/now-online-6th-access-to-medicine-index). Well worth reading, but just to pull out a couple of quotes.

"The Index found that the industry’s engagement in such R&D is focused on five diseases, with half of all such activity targeting malaria, HIV/AIDS, tuberculosis, Chagas disease and leishmaniasis....But 45 diseases have been identified as a priority for R&D by the WHO and others".

Diseases with the least attention include; several haemorrhagic fevers; several parasitic worm diseases; syphilis; cholera and diarrhoea caused by E coli. Some are rarer diseases while some areas receive less support from governments and global donors.

Current [WHO list of neglected diseases](http://www.who.int/neglected_diseases/diseases/en/).

Buruli ulcer
Chagas disease
Dengue and Chikungunya
Dracunculiasis (guinea-worm disease)
Echinococcosis
Foodborne trematodiases
Human African trypanosomiasis (sleeping sickness)
Leishmaniasis
Leprosy (Hansen's disease)
Lymphatic filariasis
Mycetoma, chromoblastomycosis and other deep mycoses
Onchocerciasis (river blindness)
Rabies
Scabies and other ectoparasites
Schistosomiasis
Soil-transmitted helminthiases
Snakebite envenoming
Taeniasis/Cysticercosis
Trachoma
Yaws (Endemic treponematoses)
