### ISSUE TITLE
Why not create an OPEN SOURCE platform dedicated to open source drug discovery ?

### ISSUE THREAD

**Issue by kevin-wad** [OpenSourceMalaria/OSM_To_Do_List#581]
Dear OSM contributors,

Instead of trying to adapt to existing platforms, why not create a brand new platform that will respond to the specific needs of open source drug discovery ?

I am a fullstack developper, I can build anything necessary, like there is no limit in what I can program. I am willing to create the perfect platform for OSM and release it as an open source project. Any open source drug discovery community could use it.

If you want to help me to build this platform, I propose to build it together taking into account all your requirements. After getting necessary information I will start coding and ask for feedbacks and change suggestions as I build it. I spent a lot of time analysing your way of using github and other tools but I still have a lot of questions before I can start.

Before talking about these specific questions, what are your thoughts about making a brand new open source platform for drug discovery ? Is it worth it for me to spend time on it and would you take part in it ?

Best Regards 
Kevin Wad

**Comment by holeung** [comment]
Hi Kevin. Nice to see your enthusiasm! I believe several others have created such platforms or at least prototype platforms. Enterprise level platforms are used in the drug industry but are expensive and usually not amenable to the open source nature of our project. I am a computational scientist but not a developer. I think developing a platform is difficult because you will have to find ways to satisfy a highly heterogeneous group of users. For example, our project involves many students, so I think ease of use must be a high priority.

Hopefully, some of the others with more expertise in this area will respond to you. I would love to hear your ideas.

**Comment by kevin-wad** [comment]
Hi Ho Leung,
Thank you for your reply! 
I really appreciate your way of answering. Indeed such a platform would have to meet the demands of heterogenous users. That's why I wanted to engage a conversation with people working on OSM as it is the pioneer community of Open source drug discovery projects. I was surprised by the lack of enthusiasm from OSM members for my proposal. But you being a computational scientist I think you will understand better what I am trying to do. 
"I would love to hear your ideas." I am working on a blockchain project whose goal is to revolutionize the drug discovery industry. In order to achieve this goal I want to get in touch with people like you. 
If you want more info about what I'm doing, let's keep the conversation private and send me an email at kevinwad.oss at gmail.com.

Thanks again dear Ho Leung!

Kevin

**Comment by mattodd** [comment]
Two things. I'd strongly urge:

1) Keeping conversations public, and at the same time
2) Devising something specific to try.  

Devising "a platform" for open source drug discovery is a huge undertaking, and it depends what you mean. We use electronic lab notebooks, sites like Github that are used for discussions and task assignment, google sheets for molecules, Datawarrior for visualisation, and so on. All these things have taken other people a great deal of time to create. So maybe start with something specific.

And are you talking of modifying existing tools, or making something from scratch?

To be honest it'd be handy to improve the opensourcemalaria.org landing page, which is out of date and does not display up to date information about targets and people contributing. If you're willing to work on that, that'd be impactful.

**Comment by drc007** [comment]
Before you embark on anything I'd suggest you have look at a commercial offering like Dotmatics (https://www.dotmatics.com) perhaps go along to their user group meeting (https://www.dotmatics.com/events/2019-10-09/dotmatics-user-symposium-cambridge). Look at all the components that they offer and you will get a better idea of what a drug discovery platform looks like. Also look at the support that would be needed to maintain the platform in the future, it needs to run 24x7 and you would need support in multiple timezones.

**Comment by holeung** [comment]
Yes, @drc007 made a great suggestion. I think where there is an unmet need is for simpler, lite versions of software like Dotmatics, that would be more suitable for academic groups, open source projects, and startup companies. In all three environments, we usually do not have support staff and resources to maintain a complex platform.

**Comment by kevin-wad** [comment]
Hi, 
I am back and now I can give you much more details about what I envision.
I think the problem is two folds. On the one hand new tools are necessary to technically make this way of researching easier. On the second hand and this might be the biggest problem, I think a new economic system is necessary. And that's what I have been building over the past year. I made an open source protocol for medical research. It envisions to finance open source researchers like you.
Have a look at the whitepaper: https://www.eticaprotocol.org
I was busy building this, but now I am back and willing to help on other issues. 

@mattodd the homepage you talked about, that doesn't seem harsh. I can rebuild it or build from scratch, depending on your needs. Please tell me exactly what you want to change and where I can access the code. 
Best regards

**Comment by senecacreek** [comment]
HI Kevin,

I just came across this initiative, and would love to learn more.  I took a look at the whitepaper, and the website.  There are some interesting concepts there.  How active is this project, and how interested are you in discussing some discrete ideas?

Best,

Keith
(CIO at Open Source Pharma Foundation)

**Comment by kevin-wad** [comment]
Hi Keith,
The project just started, it was launched on september 28th 2019 to be precise. Concerning activity for now people are just discovering the project through word of mouse with an average of 20 to 50 visits on the website every day since 28th september.
The goal is to create a neutral protocol devoted to finance open source medical research without intellectual property.
For this purpose the use of blockchain was necessary. I am a developper specialised in blockchain and I have been working on Etica for more than a year. It is my belief the concepts behind this protocol could be revolutionary if put in the right hands.
It appears your organisation has been working on open source pharma for much longer than I've been and I would be pleased to share my vision with you. 
If you have any question about Etica I would be glad to answer them.
I am open to discuss discrete ideas, you can contact me here or on kevinwad.oss at gmail dot com.

Best regards

Kevin Wad

**Comment by spirobel** [comment]
> Before you embark on anything I'd suggest you have look at a commercial offering like Dotmatics (https://www.dotmatics.com) perhaps go along to their user group meeting (https://www.dotmatics.com/events/2019-10-09/dotmatics-user-symposium-cambridge). Look at all the components that they offer and you will get a better idea of what a drug discovery platform looks like. Also look at the support that would be needed to maintain the platform in the future, it needs to run 24x7 and you would need support in multiple timezones.

I really want to take a look at this. I recently wrote this project management plugin for discourse: [https://meta.discourse.org/t/projects-management-plugin/143712](https://meta.discourse.org/t/projects-management-plugin/143712 )
Maybe we can develop an orthogonal plugin that can be combined with this. So you could use the project management plugin to assign and schedule tasks and a different plugin to create a substance database. We could also make it so that you can mention certain substances in other topics/tasks. similar like how you can use the poll plugin in discourse. 
The discourse ui has this "poll builder".
![Screenshot_2020-03-10 Discourse Meta](https://user-images.githubusercontent.com/43391631/76299443-628c7500-62bb-11ea-9b5a-229b40625e77.png)
![Screenshot_2020-03-10 Discourse Meta(1)](https://user-images.githubusercontent.com/43391631/76299511-85b72480-62bb-11ea-8529-949e992b8fe1.png)
![Screenshot_2020-03-10 Discourse Meta(2)](https://user-images.githubusercontent.com/43391631/76299518-88b21500-62bb-11ea-8f53-7ed082b8120e.png)
that automatically creates these markdown elements for you and inserts them into your post. In a similar fashion we could make an ui element that lets you select a substance from a database that you want to work on. Every substance could also have its own topic where information can be collaboratively added or changed. This means all the information is kept in one place while you can still easily reference it in the task scheduling part or other general discussions. This is all just brainstorming for now as I haven't fully understood what dotmatics is doing and how the drug discovery process works. It would be best to find a dotmatics user in berlin, that I can talk to. 
I am one of the co-organizers of this event: https://www.meetup.com/de-DE/Open-Source-Coding-in-Berlin/events/krsnnrybcdbfb/ and we are searching for something  meaningful to work on. So maybe I can convince others to help, if we could find a real user. I also think its best to not write this from scratch, but do this as discourse plugins. If you want to learn more about discourse check out this: [www.discourse.org](https://www.discourse.org/) Its basically an open source forum software that already includes most of the features that are necessary for collaborative editing of data. login, registration, posting, moderating all of this stuff is already handled in a professional way.

**Comment by mattodd** [comment]
Closing as not followed up
